---
# tasks file configure.yml

- name: Ensuer MySQL Datadir is exists.
  file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: "{{ mysql_daemon_user }}"
    group: "{{ mysql_daemon_user }}"
    mode: 0755

- name: Copy my.cnf global MySQL configuration.
  template:
    src: my.cnf.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: 0644

- name: Ensure MySQL is started and enabled on boot.
  service:
    name: "{{ mysql_daemon }}"
    state: started
    enabled: yes
