---
# tasks file for ansible-role-mysql

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

  # Configure MySQL.
- include: configure.yml
- include: secure-installation.yml
- include: users.yml
- include: replication.yml
